config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'panels#home'
  resources :panels, :only => [:new, :create]
  patch 'panel', to: 'panels#update'
  get 'page', to: 'panels#page'
  get 'admin/gallery', to: 'panels#view', as: 'gallery'
  get 'admin/edit', to: 'panels#edit'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/panel.rb
class Panel < ActiveRecord::Base
    has_attached_file :image, default_url: "/assets/missing404.jpeg"
    validates :title, presence: true
    validates :page, presence: true
    validates :width, presence: true
    validates :height, presence: true
    validates_attachment :image, presence: true,
        content_type: { content_type: ["image/jpeg", "image/png"] }
        
    include OrderQuery
    order_query :order_home,
        [:page, :asc, unique: true]
    
    def forwards
        position = Panel.all.order_home_at(self)
        position.next
    end
    
    def backwards
        position = Panel.all.order_home_at(self)
        position.previous
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  after_initialize :init
         
  def init
    self.rank ||= "commoner"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :check_rank
  
  def check_rank
    if user_signed_in?
      @user = current_user
      return @user.rank
    else
      return "commoner"
    end
  end
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController
  def home
  end
  
  def new
    @panel = Panel.new
  end
end

app/controllers/panels_controller.rb
class PanelsController < ApplicationController
  def home
    if Panel.exists?(Panel.all.order_home.last)
      @panel = Panel.all.order_home.last
    else
      @panel = Panel.new
    end
  end
  
  def new
    @image = Panel.new(
      :title => "",
      :hovertext => "",
      :comment => ""
      )
    if Panel.exists?(Panel.all.order_home.last)
      @last_page = Panel.all.order_home.last.page
    else
      @last_page = 1
    end
  end
  
  def page
    if Panel.exists?(Panel.find_by page: params[:page])
        @panel = Panel.find_by page: params[:page]
    else
        @panel = Panel.new
    end
    
    @first_page = first_page
    @last_page = last_page
    unless @panel.page == first_page
      @previous_page = @panel.backwards.page
    end
    unless @panel.page == last_page
      @next_page = @panel.forwards.page
    end
  end
  
  def view
    @panels = Panel.all
  end
  
  def edit
    if Panel.exists?(Panel.find_by page: params[:page])
      @panel = Panel.find_by page: params[:page]
    else
      @panel = Panel.new
    end
    @page = @panel.page
  end
  
  def create
    @panel = Panel.new(panel_params)
    if @panel.save
      flash[:success] = "Successfully saved panel to database."
      redirect_to page_path(page: @panel.page)
    else
      flash[:danger] = @panel.errors.full_messages.join(", and")
      redirect_to new_panel_path
    end
  end
  
  def update
    @panel = Panel.find_by page: params[:old_page]
    if params[:destroy_panel]
      @panel.delete
      flash[:warning] = "Panel deleted."
      redirect_to gallery_path
    else 
      if @panel.update(panel_params)
        flash[:success] = "Successfully updated panel in database."
        redirect_to page_path(page: @panel.page)
      else
        flash[:danger] = @panel.errors.full_messages.join(", and")
        redirect_to admin_edit_path(page: params[:old_page])
      end
    end
    
  end
  
  def first_page
    Panel.order(:page).first.page
  end
  
  def last_page
    Panel.order(:page).last.page
  end
  
  private
    def panel_params
      params.require(:panel).permit(:title, :image, :page, :width, :height, :hovertext, :comment)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/panel_helper.rb
module PanelHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webcomic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div margin=10px></br></div>
  <div class="container text-center"> <!-- Header and navbar -->
    <%= image_tag("https://placeholder.baker.com/800x200", style: 'width:75%', id: "header") %>
    </br>
    <div class="col-md-8 col-md-offset-2 btn-group">
      
      <div class="pull-left">
        <%= link_to "Home", root_path, class: "btn btn-default" %>
        <%= link_to "Blog", "#", class: "btn btn-default" %>
      </div>
      
      <div class="pull-right">
        <% if check_rank == "god" %>
          <%= link_to "New Page", new_panel_path, class: "btn btn-default" %>
          <%= link_to "Edit Pages", gallery_path, class: "btn btn-default" %>
        <% end %>
        <% if user_signed_in? %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default" %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: "btn btn-default" %>
        <% end %>
      </div>
      
    </div>
  </div> 

  <div class="container text-center">
    <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: "alert alert-#{type}" unless message.blank? %>
    <% end %>
  </div>
  
  <%= yield %>

</body>
</html>

app/views/panels/_page_buttons.html.erb
<div class="col-md-4 col-md-offset-4">
    <nav aria-label="...">
        <ul class="pager">
                <% if @panel.title == 'Missing' %>
                    <li><%= link_to "Turn Back!", :back, class: "btn btn-default" %></li>
                <% else %>
                    <% if @panel.page != @first_page %>
                        <li><%= link_to "<<<", page_path(page: @first_page), class: "btn btn-default" %></li>
                        <li><%= link_to "<--", page_path(page: @previous_page ), class: "btn btn-default" %></li>
                    <% end %>
                    
                    <% if @panel.page != @last_page %>
                        <li><%= link_to "-->", page_path(page: @next_page), class: "btn btn-default" %></li>
                        <li><%= link_to ">>>", page_path(page: @last_page), class: "btn btn-default" %></li>
                    <% end %>
                <% end %>
        </ul>
    </nav>
</div>

app/views/panels/_panel.html.erb
<% gallery.each do |panel| %>
    <div class="col-md-2">
        <%= link_to admin_edit_path(page: panel.page), class: "thumbnail" do %>
            <%= image_tag panel.image.url, title: panel.hovertext %>
            <div class="caption">
                <h4><%= panel.title %></h4>
            </div>
        <% end %>
    </div>
<% end %>

app/views/panels/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            
            <h2 class="text-center">Edit Panel</h2>
            <div class="well">
                <%= form_for @panel, url: panel_path, :method => :patch, html: {multipart: true} do |f| %>
                    <div class="form-group">
                        <%= f.label :title %>
                        <%= f.text_field :title, class: 'form-control', value: @panel.title %>
                    </div>
                    <div class="thumbnail">
                        <%= image_tag @panel.image.url, title: @panel.hovertext %>
                    </div>
                    <div class="form-group">
                        <%= f.label :panel, "New Image" %>
                        <%= f.file_field :image, class: 'form-control', value: nil %>
                    </div>
                    <div class="form-group">
                        <%= f.label :page %>
                        <%= f.number_field :page, in: 1..1000, step: 1, value: @panel.page %>
                        &nbsp;
                        <%= f.label :width %>
                        <%= f.number_field :width, in: 100..1000, step: 100, value: @panel.width %>
                        &nbsp;
                        <%= f.label :height %>
                        <%= f.number_field :height, in: 100..1000, step: 100, value: @panel.height %>
                    </div>
                    <div class="form-group">
                        <%= f.label :hovertext, "Hover Text" %>
                        <%= f.text_field :hovertext, class: 'form-control', value: @panel.hovertext %>
                        <%= f.label :comment %>
                        <%= f.text_area :comment, class: 'form-control', value: @panel.comment %>
                    </div>
                    <%= hidden_field_tag 'old_page', @page %>
                    <% if @panel.title == "Missing" %>
                        <p>There's nothing here! You can't update or delete nothing; something must have gone wrong.</p>
                    <% else %>
                        <%= f.submit 'Update', class: 'btn btn-default' %>
                        <%= submit_tag 'Delete', name: 'destroy_panel', data: { confirm: 'Are you sure you want to delete this panel?' }, class: 'btn btn-danger pull-right' %>
                    <% end %>
                <% end %>
                
            </div>
        </div>
    </div>
</div>

app/views/panels/home.html.erb
<div class="container"> 
    <div class="row"> <!-- Panel and other content -->
        <div class="col-md-8 col-md-offset-2">
            <% unless @panel.title == 'Missing' %>
                <h2 class='text-center'><%= @panel.title %></h2>
            <% end %>
            <%= image_tag @panel.image.url, width: @panel.width, height: @panel.height, title: @panel.hovertext, class: "center_panel" %>
        </div>
    </div>
    
    <div class="row text-center" id="button_row">
        <%= render partial: "page_buttons", locals: { panel: @panel } %>
    </div>
    
    <div class="row"> <!-- Footer -->
        <div class="well col-md-8 col-md-offset-2 text-center">
            <%= @panel.comment %>
        </div>
    </div>
    
    <div margin: 20px></br></div>
</div>

app/views/panels/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            
            <h2 class="text-center">Create New Panel</h2>
            <div class="well">
                <%= form_for @image, url: panels_path, html: {multipart: true} do |f| %>
                    <div class="form-group">
                        <%= f.label :title %>
                        <%= f.text_field :title, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :panel %>
                        <%= f.file_field :image, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :page %>
                        <%= f.number_field :page, in: 1..1000, step: 1, value: @last_page %>
                        &nbsp;
                        <%= f.label :width %>
                        <%= f.number_field :width, in: 100..1000, step: 100, value: 600 %>
                        &nbsp;
                        <%= f.label :height %>
                        <%= f.number_field :height, in: 100..1000, step: 100, value: 800 %>
                    </div>
                    <div class="form-group">
                        <%= f.label :hovertext, "Hover Text" %>
                        <%= f.text_field :hovertext, class: 'form-control', placeholder: "This will show up when the panel is hovered over!" %>
                        <%= f.label :comment %>
                        <%= f.text_area :comment, class: 'form-control', placeholder: "A note to go beneath the panel." %>
                    </div>
                    <%= f.submit 'Upload', class: 'btn btn-default' %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/panels/page.html.erb
<div class="container"> 
    <div class="row"> <!-- Panel and other content -->
        <div class="col-md-8 col-md-offset-2">
            <% unless @panel.title == 'Missing' %>
                <h2 class='text-center'><%= @panel.title %></h2>
            <% end %>
            <%= image_tag @panel.image.url, width: @panel.width, height: @panel.height, title: @panel.hovertext, class: "center_panel" %>
        </div>
    </div>
    
    <%= render "page_buttons" %>
    
    <div class="row"> <!-- Footer -->
        <div class="well col-md-8 col-md-offset-2 text-center">
            <%= @panel.comment %>
        </div>
    </div>
    
    <div margin: 20px></br></div>
</div>

app/views/panels/view.html.erb
<div class="container">
    <h3 class="text-center">Page Gallery</h3>
    <div class="row text-center">

        <%= render partial: "panel", locals: {gallery: Panel.order(:page)} %>    
        
    </div>
    
    
</div>